openapi: 3.0.0

servers:
  - url: "/api/productPrice"

info:
  version: v1
  title: PricesService - API
  description: |-

    This API offers endpoints for relations between prices, brand, and products

  contact:
    name: imunoz
    email: imunozgonzalez@gmail.com

paths:
  /{productId}/{brandId}:
    parameters:
        - name: productId
          in: path
          description: |-
            Product Id.
          required: true
          schema:
            type: integer
        - name: brandId
          in: path
          description: |-
            Brand Id.
          required: true
          schema:
            type: integer
        - name: dateApplication
          in: query
          description: |-
            Application date of price list. (yyyy-MM-dd'T'HH:mm:ss)
          required: true
          schema:
            type: string

    get:
      summary: Get product's price
      description: |-
        Get product's price from productId, brandId and application date.
      responses:
        "200":
          description: OK     
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductPriceSimple" 
        "400":
          $ref: "#/components/responses/clientError" 
        "404":
          $ref: "#/components/responses/notFoundError"         

components:
  schemas:
    ProductPriceSimple:
       description: Product Price without priority
       allOf:
        - properties:
            productId:
              description: Product's identified
              type: integer
              maxLength: 19
              minimum: 0
              example: 1
            startDate:
              description: Start date applied
              type: string
              format: date-time
              example: '2021-06-15T10:00:00'
            endDate:
              description: End date applied
              type: string
              format: date-time
              example: '2021-06-16T10:00:00'  
            priceList:
              description: Price List identified
              type: integer
              maxLength: 19
              minimum: 0
              example: 1
            price:
              description: Price value
              type: number
              minimum: 0
              example: 33.3
            curr:
              description: currency ISO
              type: string
              maxLength: 3
              minLength: 0
              example: 'EUR'
            brandId:
              description: Brand's identified
              type: integer
              maxLength: 19
              minimum: 0
              example: 1
              
  responses:
    notFoundError:
      description: Element not found
    
    clientError:
      description: Client error